#+TITLE: Emacs Configuration
#+AUTHOR: Gokul Bejoy

* Backup file
Put all backup files in a separate directory so that they don't clutter up

#+begin_src emacs-lisp
  (setq backup-directory-alist '(("." . "~/.local/share/emacs/backups"))
	backup-by-copying t
	delete-old-versions t
	kept-new-versions 6
	kept-old-versions 2
	version-control t)
#+end_src

* Custom file
Put all config written by customize in a separate file in the
user-emacs-directory.

#+begin_src emacs-lisp
  (setq custom-file (locate-user-emacs-file "custom.el"))
  (load custom-file :no-error-if-file-is-missing)
#+end_src

* Package management

** Add MELPA
[[https://melpa.org][MELPA]] hosts some packages that I use frequently. Following code adds
it to the package list.

#+begin_src emacs-lisp
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (package-initialize)
#+end_src

** Setup use-package
John Wiegley's [[https://github.com/jwiegley/use-package][use-package]] is somewhat of a macro that helps managing
packages a lot easier with easier defering of packages. From version
29, it is a built-in package. This code installs the package if it is
an older version.

#+begin_src emacs-lisp
  (when (< emacs-major-version 29)
    (unless (package-installed-p 'use-package)
      (unless package-archive-contents
	(package-refresh-contents))
      (package-install 'use-package)))
#+end_src

#+RESULTS:

Now always install the package by default if not available since it
helps me avoid writing ":ensure t" everywhere.

#+begin_src emacs-lisp
  (setq use-package-always-ensure t)
#+end_src

* Appearance

** Fonts

Sets monospaced and proportional fonts for emacs.

#+begin_src emacs-lisp
  (let ((mono-spaced-font "Source Code Pro")
	(proportionately-spaced-font "Inter"))
    (set-face-attribute 'default nil
			:family mono-spaced-font
			:height 140)
    (set-face-attribute 'fixed-pitch nil
			:family mono-spaced-font
			:height 1.0)
    (set-face-attribute 'variable-pitch nil
			:family
			proportionately-spaced-font
			:height 1.0))
#+end_src

** Theme

#+begin_src emacs-lisp
  (use-package ef-themes
    :ensure t
    :config
    (load-theme 'ef-light :no-confirm-loading))
#+end_src

* Misc

** Always use y-or-n-p
Use y or n everywhere instead of yes or no

#+begin_src emacs-lisp
  (setopt use-short-answers t)
#+end_src

** User details
Set details about the user like name, mail, etc

#+begin_src emacs-lisp
  (setq user-full-name "Gokul Bejoy")
  (setq user-mail-address "imgokulbejoy@gmail.com")
#+end_src


* Packages

** corfu
In-buffer completion.

#+begin_src emacs-lisp
  (use-package corfu
    :init
    (global-corfu-mode)
    :bind (:map corfu-map ("<tab>" . corfu-complete))
    :config
    (setq tab-always-indent 'complete)
    (setq corfu-min-width 20)
    (setq corfu-popupinfo-delay '(1.25 . 0.5))
    (corfu-popupinfo-mode 1))
#+end_src

** dired
Emacs file manager

#+begin_src emacs-lisp
  (use-package dired
    :ensure nil
    :commands (dired)
    :hook
    ((dired-mode . dired-hide-details-mode)
     (dired-mode . hl-line-mode))
    :config
    (setq dired-recursive-copies 'always)
    (setq dired-recursive-deletes 'always)
    (setq delete-by-moving-to-trash t)
    (setq dired-dwim-target t))
#+end_src

** dired-subtree
Gives sneakpeek into directory contents

#+begin_src emacs-lisp
  (use-package dired-subtree
    :after dired
    :bind
    ( :map dired-mode-map
      ("<tab>" . dired-subtree-toggle)
      ("TAB" . dired-subtree-toggle)
      ("<backtab>" . dired-subtree-remove)
      ("S-TAB" . dired-subtree-remove))
    :config
    (setq dired-subtree-use-backgrounds nil))
#+end_src

** elfeed
Feed reader for emacs

#+begin_src emacs-lisp
  (use-package elfeed
    :bind
    ("C-c f v" . elfeed))
#+end_src


Here contains a list of feeds I subscribe to
#+begin_src emacs-lisp
  (setq elfeed-feeds
	'(("https://krebsonsecurity.com/feed/" tech security)
	  ("https://lobste.rs/rss" tech programming dev)
	  ("https://hnrss.github.io/frontpage" tech programming dev career)
	  ("https://www.slowernews.com/rss.xml" global essays)
	  ("https://planet.emacslife.com/atom.xml" emacs blog)
	  ("https://lwn.net/headlines/rss" linux news)
	  ("https://hackernoon.com/feed" tech programming dev career science)
	  ("https://www.reddit.com/r/linux/.rss" reddit linux)
	  ("https://rss.slashdot.org/Slashdot/slashdotMain" tech news science)
	  ("https://www.phoronix.com/rss.php" linux hardware)
	  ("https://liliputing.com/feed" hardware mobile linux pc)
	  ("https://www.technologyreview.com/feed/" tech science academic)
	  ("https://www.reddit.com/r/malayalammovies/.rss" reddit movies)
	  ("https://www.reddit.com/r/kollywood/.rss" reddit movies)
	  ("https://www.reddit.com/r/emacs/.rss" reddit emacs)))
#+end_src

** gptel
Interface to LLM models

#+begin_src emacs-lisp
  (use-package gptel)
#+end_src

#+begin_src emacs-lisp
  (gptel-make-openai "llama.cpp"
		     :stream t
		     :protocol "http"
		     :host "localhost:8000"
		     :models '(test))
#+end_src

#+RESULTS:
: #s(gptel-openai "llama.cpp" "localhost:8000" #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_18> "http" t "/v1/chat/completions" nil (test) "http://localhost:8000/v1/chat/completions" nil nil)

** howm
Japanese wiki for efficient notetaking.

#+begin_src emacs-lisp
  (use-package howm)
#+end_src

#+RESULTS:

** ledger-mode
Major mode for editing ledger files
#+begin_src emacs-lisp
  (use-package ledger-mode
    :mode "\\.dat\\'")
#+end_src

** magit
Greatest git interface that shows all options available better than
git-cli.

#+begin_src emacs-lisp
  (use-package magit)
#+end_src

** marginalia
Adds useful descriptions about completion candidates.

#+begin_src emacs-lisp
  (use-package marginalia
    :init
    (marginalia-mode))
#+end_src

** nov.el
Used to read EPUBs

#+begin_src emacs-lisp
  (use-package nov
    :config
    (add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode)))
#+end_src

#+RESULTS:
: t

** orderless
Matches completion styles irrespective of order of each strings. Each
string is separated by a space.

#+begin_src emacs-lisp
  (use-package orderless
    :custom
    (completion-styles '(orderless basic))
    (completion-category-defaults nil)
    (completion-category-overrides '((file (styles partial-completion)))))
#+end_src

** org
Dynamic note-taking format

#+begin_src emacs-lisp
  (use-package org
    :bind
    (("C-c o a" . org-agenda)
     ("C-c o c" . org-capture))
    :ensure nil
    :custom
    (org-directory "~/Documents/org/")
    (org-agenda-files (list "todo.org")))
#+end_src

#+RESULTS:
: org-capture

*** org-capture
Capture ideas quickly from anywhere

#+begin_src emacs-lisp
    (use-package org-capture
      :ensure nil
      :config
      (setq org-capture-templates
	    '(("i" "Inbox" entry (file "inbox.org")
	       "* %?\n Entered on %U")
	      ("t" "Tasks")
	      ("tn" "Todo now" entry (file "todo.org")
	       "* TODO %?\n")
	      ("td" "Todo within DEADLINE" entry (file "todo.org")
	       "* TODO %?\nDEADLINE: %^{Deadline}t")
	      ("ts" "Todo on SCHEDULE" entry (file "todo.org")
	       "* TODO %?\nSCHEDULED: %^{Scheduled}t")
	      ("tt" "Todo today" entry (file "todo.org")
	       "* TODO %?\nDEADLINE: %U")
	      ("j" "Journal" entry (file+datetree "journal.org")
	       "* %^{Entry title}\nEntered on %U\n %?\n %i")
	      ("p" "Project")
	      ("pc" "Project Create" entry (file "todo.org")
	       "* %^{Project Name}\n* %i?\n")
	      ("pa" "Project Add" entry (file+headline "todo.org" "%^{headline}")
	       "* %i?\n"))))
#+end_src

#+RESULTS:
: t


** pdf-tools
PDF reader in emacs using poppler library

#+begin_src emacs-lisp
  (use-package pdf-tools
    :ensure t
    :magic ("%PDF" . pdf-view-mode)
    :config
    (pdf-tools-install :no-query))
#+end_src

** savehist
Saves user-inputs and displays last used choices on top.

#+begin_src emacs-lisp
  (use-package savehist
    :ensure nil
    :init
    (savehist-mode))
#+end_src

** trashed
Trash can management

#+begin_src emacs-lisp
  (use-package trashed
    :commands (trashed)
    :config
    (setq trashed-use-header-line t)
    (setq trashed-sort-key '("Date deleted" . t))
    (setq trashed-date-format "%Y-%m-%d %H:%M:%S"))
#+end_src

** vertico
Vertical minibuffer completion package.

#+begin_src emacs-lisp
  (use-package vertico
    :ensure t
    :init
    (vertico-mode))
#+end_src

** which-key
Shows available keybinds while performing an operation.

#+begin_src emacs-lisp
  (use-package which-key
    :ensure t
    :init
    (which-key-mode))
#+end_src

* Programming

** [[https://clojure.org][Clojure]]

*** clojure-mode
Minor-mode for clojure

#+begin_src emacs-lisp
  (use-package clojure-mode)
#+end_src

*** CIDER
Interactively program in clojure

#+begin_src emacs-lisp
  (use-package cider)
#+end_src

